from . import index_controller
from . import genre_controller
from . import song_edit_controller
from . import song_add_controller
from . import song_controller
from . import year_controller
from . import songmaker_controller
from . import song_delete_controller
from . import songmaker_edit_controller
from . import songmaker_add_controller
from . import songmaker_delete_controller
from . import registration_controller